#!/usr/bin/env bash
#
# @(#) build-roadrunner-parts
#
# Copyright © 2021-2023 Revolution Robotics, Inc.
#
: ${APT_CMD:='/usr/bin/apt'}
: ${CAT_CMD:='/bin/cat'}
: ${CURL_CMD:='/usr/bin/curl'}
: ${CHMOD_CMD:='/bin/chmod'}
: ${GIT_CMD:='/usr/bin/git'}
: ${GPG_CMD:='/usr/bin/gpg'}
: ${GREP_CMD:='/usr/bin/grep'}
: ${MKDIR_CMD:='/bin/mkdir'}
: ${READLINK_CMD:='/bin/readlink'}
: ${TEE_CMD:='/usr/bin/tee'}

: ${NPROC:=$(nproc)}
: ${BUILD_SUITE_BRANCH_DEFAULT:='debian_bullseye_rr01'}
: ${BUILD_DIR:="${0%/*}/roadrunner-debian"}
: ${CA_URL:='@CA_URL@'}
: ${CA_FINGERPRINT:='@CA_FINGERPRINT@'}
: ${X509_GENKEY:="@X509_GENKEY@"}
: ${SIGNING_KEY:="@SIGNING_KEY@"}
: ${HOST_GW_IPV4:='@GW_IPV4@'}
: ${DEBIAN_PROXY:="-p http://${HOST_GW_IPV4}:3142/deb.debian.org/debian"}

# OS-agnstoic readlink for existent files/directories.
resolve-existing ()
{
    if $READLINK_CMD --version 2>&1 | $GREP_CMD -q 'coreutils'; then
        $READLINK_CMD -e -- "$@"
    else
        $READLINK_CMD -f N "$@"
    fi
}

install-prerequisites ()
{
    $APT_CMD update
    $APT_CMD -qy install curl gawk iproute2
    $APT_CMD -qy remove --purge mawk

    if test ."$HOST_GW_IPV4" != .'' &&
            $CURL_CMD "${HOST_GW_IPV4}:3142" &>/dev/null; then
        $CAT_CMD >/etc/apt/apt.conf.d/10acng-proxy <<EOF
Acquire::http::Proxy "http://${HOST_GW_IPV4}:3142";
EOF
    else
        DEBIAN_PROXY=''
    fi

    $APT_CMD -qy install autoconf automake autopoint bc \
        binfmt-support binutils bison build-essential cmake \
        coreutils debootstrap device-tree-compiler \
        ed flex g++ gcc git gpg groff help2man \
        libssl-dev libtool lzop m4 make parted qemu \
        qemu-user-static rsync sudo u-boot-tools unzip \
        upx-ucl zstd
    $APT_CMD -qy install binutils-arm-linux-gnueabihf
    $APT_CMD -qy install cpp-arm-linux-gnueabihf
    $APT_CMD -qy install gcc-arm-linux-gnueabihf
    $APT_CMD -qy install g++-arm-linux-gnueabihf

    $CURL_CMD -sLo /usr/bin/install-smallstep \
         "https://raw.githubusercontent.com/revolution-robotics/roadrunner-debian/debian_bullseye_rr01/revo/resources/smallstep/install-smallstep"
    $CHMOD_CMD +x /usr/bin/install-smallstep
    $CURL_CMD -sLo /usr/bin/bootstrap-smallstep \
         "https://raw.githubusercontent.com/revolution-robotics/roadrunner-debian/debian_bullseye_rr01/revo/resources/smallstep/bootstrap-smallstep"
    $CHMOD_CMD +x /usr/bin/bootstrap-smallstep
    case $($UNAME_CMD -m) in
        armv7l|aarch64|arm64) bootstrap-smallstep ;;
        amd64|x86_64) $SUDO_CMD install-smallstep ;;
    esac

    $CURL_CMD -sL https://ftp-master.debian.org/keys/release-11.asc |
        $GPG_CMD --import --no-default-keyring \
             --keyring /usr/share/keyrings/debian-bullseye-release.gpg
}

clone-build-suite ()
{
    local build_suite_commit=$1

    if ! $MKDIR_CMD -p "$BUILD_DIR"; then
        echo "${FUNCNAME[0]}: $BUILD_DIR: Permission denied" >&2
        return 1
    fi
    git config --global init.defaultBranch main || return $?
    git -C "$BUILD_DIR" init || return $?
    git -C "$BUILD_DIR" remote add origin \
        https://github.com/revolution-robotics/roadrunner-debian.git || return $?
    git -C "$BUILD_DIR" fetch || return $?
    if test ."$build_suite_commit" != .''; then
        git -C "$BUILD_DIR" checkout -b "commit-${build_suite_commit:0:6}" \
            "$build_suite_commit" || return $?
    else
        git -C "$BUILD_DIR" switch "$BUILD_SUITE_BRANCH_DEFAULT"  || return $?
    fi
}

build-parts ()
{
    MACHINE=revo-roadrunner-mx7 \
        "${BUILD_DIR}/revo_make_debian.sh" -c deploy |&
        $TEE_CMD "${BUILD_DIR}/build.log" || return $?
    MACHINE=revo-roadrunner-mx7 \
        "${BUILD_DIR}/revo_make_debian.sh" \
        $DEBIAN_PROXY -j "$NPROC" -c bootloader |&
        $TEE_CMD -a "${BUILD_DIR}/build.log" || return $?
    MACHINE=revo-roadrunner-mx7 \
        "${BUILD_DIR}/revo_make_debian.sh" \
        $DEBIAN_PROXY -j "$NPROC" -c scripts |&
        $TEE_CMD -a "${BUILD_DIR}/build.log" || return $?
    MACHINE=revo-roadrunner-mx7 \
        "${BUILD_DIR}/revo_make_debian.sh" \
        $DEBIAN_PROXY -j "$NPROC" -c devicetree |&
        $TEE_CMD -a "${BUILD_DIR}/build.log" || return $?
}

if test ."$0" = ."${BASH_SOURCE[0]}"; then
    declare script=''
    declare script_name=''
    declare script_dir=''

    script=$(resolve-existing "$0") || exit $?
    script_name=${script##*/}
    script_dir=${script%/*}

    declare build_suite_commit=$1

    echo '*** Build Roadrunner Parts ***' >&2
    install-prerequisites || exit $?
    clone-build-suite "$build_suite_commit" || exit $?
    build-parts
fi
