#!/usr/bin/env bash
#
# @(#) container-build-release
#
# Copyright © 2021-2023 Revolution Robotics, Inc.
#
: ${AWK_CMD:='/usr/bin/gawk'}
: ${CAT_CMD:='/bin/cat'}
: ${DF_CMD:='/bin/df'}
: ${FINDMNT_CMD:='/bin/findmnt'}
: ${INSTALL_CMD:='/usr/bin/install'}
: ${PODMAN_CMD:='/usr/bin/podman'}
: ${READLINK_CMD:='/bin/readlink'}
: ${SUDO_CMD:='/usr/bin/sudo'}
: ${ZFS_CMD:='/sbin/zfs'}

# OS-agnstoic readlink for existent files/directories.
resolve-existing ()
{
    if $READLINK_CMD --version 2>&1 | $GREP_CMD -q 'coreutils'; then
        $READLINK_CMD -e -- "$@"
    else
        $READLINK_CMD -f N "$@"
    fi
}

create-external-volume ()
{
    local build_products_dir=$1
    local volume_name=$2

    local dest_dir=${build_products_dir}/${volume_name}

    pr-info "Populating external volume..."

    local fs_mount=''
    local fs_type=''

    fs_mount=$(
        $DF_CMD "$build_products_dir" |
            $AWK_CMD 'NR > 1 { print $NF }'
            ) || return $?
    fs_type=$(
        $FINDMNT_CMD -n "$fs_mount" |
            $AWK_CMD '{ print $3 }'
           ) || return $?

    if test ."$fs_type"  = .'zfs'; then
        local dataset=''

        dataset=$(
            $DF_CMD "$build_products_dir" |
                $AWK_CMD 'NR > 1 { print $1 }'
               ) || return $?


        if ! $SUDO_CMD $ZFS_CMD create -p -o mountpoint="${dest_dir}" \
             "${dataset}/${volume_name}"; then
            pr-err "${FUNCNAME[0]}: ${dest_dir}: Cannot create directory"
            return 1
        fi
    else
        if ! $SUDO_CMD $INSTALL_CMD -d "${dest_dir}"; then
            pr-err "${FUNCNAME[0]}: ${dest_dir}: Cannot create directory"
            return 2
        fi
    fi

    echo "$dest_dir"
}

run-builder ()
{
    local builder_name=$1
    local dest_dir=$2
    local mount_dir=$3

    if command -v aa-enabled >/dev/null &&
            test ."$(aa-enabled)" = .'Yes'; then

        pr-info "Running with:  apparmor=unconfined"

        $SUDO_CMD $PODMAN_CMD run -it --rm --privileged \
             --security-opt apparmor=unconfined \
             -v "${dest_dir}:${mount_dir}:rshared,rbind,exec,dev,suid,rw" \
             "localhost/${builder_name}"
    else

        pr-info "Running with:  privilege"

        $SUDO_CMD $PODMAN_CMD run -it --rm --privileged \
               -v "${dest_dir}:${mount_dir}:rshared,rbind,exec,dev,suid,rw" \
               "localhost/${builder_name}"
    fi

    # $SUDO_CMD $PODMAN_CMD rmi "$builder_id" &>/dev/null
}

if test ."$0" = ."${BASH_SOURCE[0]}"; then
    declare script=''
    declare script_dir=''
    declare script_name=''

    script=$(resolve-existing "$0") || exit $?
    script_dir=${script%/*}
    script_name=${script##*/}

    source "${script_dir}/build-builder-image"

    declare client=${1:-'UD'}
    declare distribution=${2:-'debian'}
    declare machine=${3-'revo-roadrunner-mx7'}

    trap 'reset-window-title; exit 1' 0 1 2 15

    source /etc/os-release

    case "$ID" in
        debian|ubuntu) enable-qemu-arm || exit $? ;;
    esac

    load-configuration "${script_dir}/build-hybrid-image.conf" || exit $?

    declare builder_id=''

    builder_id=$(
        build-builder "$builder_name" "$builder_image" "$builder_tag" \
                      "$build_script" "$client"
              ) || exit $?

    if test ."$builder_id" = .''; then
        pr-err "${script_name}: Cannot build builder image"
        exit 3
    fi

    declare volume_name=''
    declare dest_dir=''

    volume_name=roadrunner-${kernel_version}_$(date -u +%Y%m%dT%H%M%SZ) || exit $?
    dest_dir=$(create-external-volume "$build_products_dir" "$volume_name") || exit $?

    $CAT_CMD >&2 <<EOF
════════════════════════════════════════════════════════════════════════════════
Client: ${client}
Builder ID: ${builder_id}
Builder image: ${builder_name}
Derived from: ${builder_image}:${builder_tag}
Destination: ${dest_dir}
────────────────────────────────────────────────────────────────────────────────
EOF
    read -p 'Press any key to continue...'

    run-builder "$builder_name" "$dest_dir" "$mount_dir" || exit $?
    reset-window-title

    trap - 0 1 2 15
fi
